version: "3.7"

services:
  postgres:
    image: postgres:18.3
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always
    environment:
      POSTGRES_DB: expenz
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - "5432"

  redis:
    image: redis:latest
    volumes:
      - redis-vol:/data
    networks:
      - app-network
    ports:
      - "6379:6379"
    restart: always

  spring-app:
    build: .
    volumes:
      - expenz-vol:/path/in/container
    networks:
      - app-network
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 5; done && java -jar Expenz.jar'

networks:
  app-network:

volumes:
  postgres-vol:
  redis-vol:
  expenz-vol:
